app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(stocksPlot1_hover = character(0), allowInputNoBinding_ = TRUE)
app$setInputs(ecoregion = "Sierra Nevada")
app$setInputs(rcp = c("rcp45", "rcp85"))
app$setInputs(gcm = c("CanESM2", "HadGEM2-ES"))
app$setInputs(ci1 = FALSE)
app$setInputs(ci1 = TRUE)
app$setInputs(showStockTable = TRUE)
app$setInputs(showStockTable = FALSE)
app$setInputs(stocksPlot1_hover = c(2050.46898490204, 870.250112237986, 209.75, 237, 209.75, 237, 1, 1, "rcp45", "Timestep", "Mean", "Min", "Max", "RCP", 1996.05, 2104.95, 650.7718, 925.9962, 55.5342392002765, 364.141545663639, 554.465661013699, 156.365752270295, character(0), character(0)), allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(navTabset = "homePanel")
app$setInputs(jumpToP5 = "click")
app$setInputs(luc = "High")
app$setInputs(luc = "Low")
app$setInputs(luc = "BAU")
app$setInputs(gcm = c("CanESM2", "CNRM-CM5", "HadGEM2-ES"))
app$setInputs(transfluxTypes = "Harvest")
app$setInputs(transfluxTypes = "Mortality")
app$setInputs(transitionTypes = "Forest Clearcut")
app$setInputs(transitionTypes = "Orchard Removal")
app$setInputs(navTabset = "homePanel")
app$setInputs(jumpToP2 = "click")
app$setInputs(smooth = TRUE)
app$setInputs(annual = TRUE)
app$setInputs(netflux = "NPP")
app$setInputs(netflux2 = c("NPP", "NECB"))
app$setInputs(netflux2 = c("NPP", "Rh", "NECB"))
app$setInputs(netflux2 = c("NPP", "Rh", "NEP", "NECB"))
app$setInputs(ecoregion = "State")
app$setInputs(navTabset = "homePanel")
app$setInputs(jumpToP4 = "click")
app$setInputs(smoothDist = TRUE)
app$setInputs(transitionsDist = "Drought")
app$setInputs(severityTypes = c("High", "Medium"))
app$setInputs(severityTypes = c("High", "Medium", "Low"))
app$setInputs(severityTypes = c("High", "Medium"))
app$setInputs(severityTypes = "High")
app$setInputs(years = c(2044, 2100))
app$setInputs(years = c(2001, 2100))
app$snapshot()
